# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7ddec8b7ce0c913ba22c9d6694499f7f015519c7970804eaff4d5abae0b93a1bf2967cd7d9d8515079ef44b913e829a29dedc4ee13ffc27851a57c175701290

test:
  secret_key_base: 81fb203639c3c0d0bcd8c0ddc27aae9103839ba8106bbe7b75feb615f344c305421e57eceea54e09be49854bd214a4cf30f086b3c7a3c57c6d4cf12d6837d9a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
